version: '3.8'

services:
  db:
    image: mysql:8
    container_name: capacity-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: capacity_planner
      MYSQL_USER: capacity_user
      MYSQL_PASSWORD: capacity_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  api:
    build: ./capacity-be
    container_name: capacity-api
    environment:
      MYSQL_URL: mysql+pymysql://capacity_user:capacity_password@db:3306/capacity_planner
      TZ: Europe/Berlin
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./capacity-be:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  fe:
    image: node:20
    container_name: capacity-fe
    working_dir: /app
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./capacity-fe:/app
    command: sh -c "pnpm install && pnpm dev --host 0.0.0.0"
    depends_on:
      - api

volumes:
  mysql_data:
