"""Initial migration - create all tables

Revision ID: 3947a09bbc8a
Revises:
Create Date: 2025-10-20 12:17:28.099723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3947a09bbc8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('holiday_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_company_day', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('holiday_id')
    )
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('employment_ratio', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('sprints',
    sa.Column('sprint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'FINISHED', name='sprintstatus'), nullable=False),
    sa.PrimaryKeyConstraint('sprint_id')
    )
    op.create_table('availability_overrides',
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('state', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'HALF', name='availabilitystate'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.sprint_id'], ),
    sa.PrimaryKeyConstraint('sprint_id', 'member_id', 'day')
    )
    op.create_index('idx_availability_sprint_member_day', 'availability_overrides', ['sprint_id', 'member_id', 'day'], unique=True)
    op.create_table('pto',
    sa.Column('pto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('pto_id')
    )
    op.create_table('sprint_roster',
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('allocation', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('assignment_from', sa.Date(), nullable=True),
    sa.Column('assignment_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.sprint_id'], ),
    sa.PrimaryKeyConstraint('sprint_id', 'member_id')
    )
    op.create_index('idx_sprint_roster_sprint_member', 'sprint_roster', ['sprint_id', 'member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sprint_roster_sprint_member', table_name='sprint_roster')
    op.drop_table('sprint_roster')
    op.drop_table('pto')
    op.drop_index('idx_availability_sprint_member_day', table_name='availability_overrides')
    op.drop_table('availability_overrides')
    op.drop_table('sprints')
    op.drop_table('members')
    op.drop_table('holidays')
    # ### end Alembic commands ###
